### PR TITLE
Milestone Design Teardown

### PR DESCRIPTION
**Pull request by shubhsk88**
## Design Teardown

This PR address the completion of the project based on the design which is to build the heatmap of the smashing magazine using the new idea. In this, we used grayscale color to show our idea for the design 

- Finished the design with grayscale elements 
- Selected the fonts for the design

### CODE REVIEW

**Review by rOluochKe — CHANGES_REQUESTED** [review]
Hello @shubhsk88 and @emiliocm9 
### You have done well in this project :clap: However, you have a few changes to make before your project could be approved.
- Run your project on w3 validator and solve the issues highlighted
validator
- Don't miss this latest articles should be placed on top of the row, use position absolute to achieve this
place on top
- Redesign your footer to much the original design, where there is 3 column put 3 columns
3 column
### Make these changes and resubmit for another code review. Good luck.
- Happy coding!

**Comment by emiliocm9** [comment]
Thank you for your feedback! 
In the original web page, my partner and I can see four columns on the footer section. We tried to find where the problem is, but we didn't find any. We would appreciate a short answer, thank you so much!
ColumnsSS

**Comment by mikenath223** [comment]
**Pull request currently under review by Michgolden Ukeje (TSE).**
Kindly exercise patience 👋

**Review by mikenath223 — APPROVED** [review]
### CONGRATULATIONS  👏👏👏

This project meets the requirements for approval.

**STATUS: APPROVED ✅**

However, before you merge kindly remove the inline comments in both your HTML files and CSS file.

Don't forget to fill the project completion form👍
Good luck with the next project.

HAPPY CODING👨‍💻

**Pull request merged**
